projeto/core/urls.py
from django.urls import path
from projeto.core import views as v


app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'), # crio uma url filha que mostra o que tem na views3
]

projeto/estoque/urls.py
from django.urls import path
from projeto.estoque import views as v


app_name = 'estoque'

urlpatterns = [
    path('', v.estoque_entrada_list, name='estoque_entrada_list'),
    path('<int:pk>/', v.estoque_entrada_detail, name='estoque_entrada_detail'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
]



projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v


app_name = 'produto'


urlpatterns = [
    path('', v.produto_list, name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit', v.ProdutoUpdate.as_view(), name='produto_edit'),
]




projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('projeto.core.urls')), # Acrescenta a url (nome da pagina)
    path('produto/', include('projeto.produto.urls')), # Acresce a url da pagina do projeto produto
    path('estoque/', include('projeto.estoque.urls')), # Acresce a url da pagina do projeto estoque
    path('admin/', admin.site.urls),
]

projeto/core/models.py
from django.db import models

# Create your models here.


class TimeStampedModel(models.Model):
    """Cria uma tabela que contém as informações da de criação do produto e sua modificação"""
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False,
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True,
    )

    class Meta:
        # A classe TimeStampedMode vai ser usada como classe pai em outro arquivo (true)
        abstract = True




projeto/estoque/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from projeto.core.models import TimeStampedModel
from projeto.produto.models import Produto


# Tupla dentro de tupla, para escolher o tipo de operação do estoque (s - saída, e -e entrada)
MOVIMENTO = (
    ('e', 'entrada'),
    ('s', 'saida'),
)


class Estoque(TimeStampedModel):
    """Cria uma tabela estoque, que contem esse campos com tais características"""
    funcionario = models.ForeignKey(User, on_delete=models.CASCADE)
    nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO)

    class Meta: # o que não vai herdar
        """Ordering é uma lista em ordem decrescente a criação de tabelas, do app core classe TimeStampedModel"""
        ordering = ('-created', )

    def __str__(self):
        # Returna em string o ítem com indice pk
        return '{} - {} - {}'.format(self.pk, self.nf, self.created.strftime('%d-%m-%Y'))

    def get_absolute_url(self):
        return reverse_lazy('estoque:estoque_entrada_detail', kwargs={'pk': self.pk})

    def nf_formated(self):
        return str(self.nf).zfill(3) # coloca zero a esquerda com limete de 3 algarismo


class EstoqueItens(models.Model):
    """Cria uma tabela EstoqueItens, que vai conter os itens para comprar ou retirar."""
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, related_name='estoques') # pega da classe estoque
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE) # pega da classe produto
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveIntegerField()

    class Meta:
        """Ordering é uma tupla que contém os índices dos campos."""
        ordering = ('pk',)

    def __str__(self):
        # retorna de mais compreensível o indice, o estoque desse indice, e o produto.
        return '{} - {} - {}'. format(self.pk, self.estoque.pk, self.produto)

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy


class Produto(models.Model):
    """Cria um banco de dados, contendo essas tabelas e caracteristicas:"""
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque mínimo', default=0)

    class Meta:
        """Permite trabalhar em outras classes. O campo produto"""
        ordering = ('produto',)

    def __str__(self):
        # Esta função permite que a saída seja legível para o humano
        return self.produto

    # Cria links diretos

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

projeto/estoque/forms.py
from django import forms
from .models import Estoque, EstoqueItens


class EstoqueForm(forms.ModelForm):

    class Meta:
        model = Estoque
        fields = '__all__'


class EstoqueItensForm(forms.ModelForm):

    class Meta:
        model = EstoqueItens
        fields = '__all__'


projeto/produto/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__' # todos os campos

projeto/core/views.py
from django.shortcuts import render,HttpResponse


def index(request):
    return render(request, 'index.html') # Aponta para o arquivo templates.index.html para exibir na tela

projeto/estoque/views.py
from django.shortcuts import render, resolve_url
from django.http import HttpResponseRedirect
from django.forms import inlineformset_factory

from .models import Estoque, EstoqueItens
from .forms import EstoqueForm, EstoqueItensForm



def estoque_entrada_list(request):
    template_name = 'estoque_entrada_list.html'
    objects = Estoque.objects.filter(movimento='e')
    context = {'object_list': objects}

    return render(request, template_name, context)


def estoque_entrada_detail(request, pk):
    template_name = 'estoque_entrada_detail.html'
    obj = Estoque.objects.get(pk=pk)
    context = {'object': obj}

    return render(request, template_name, context)


def estoque_entrada_add(request):
    template_name = 'estoque_entrada_form.html'
    estoque_form = Estoque()
    item_estoque_formset = inlineformset_factory(
        Estoque, # Classe pai
        EstoqueItens, # Classe filha
        form=EstoqueItensForm,  # formulário a ser usado
        extra=0, # indicamos quantos itens teremos inicialmente quando for renderizado em html
        #can_delete=False: Ignoramos a opção de deletar o formulário.
        min_num=1, # indicamos a quantidade de intem da lista
        validate_min=True, # habilitamos a validação do formulário
    )
    if request.method == 'POST':
        form = EstoqueForm(request.POST, instance=estoque_form, prefix='main')
        formset = item_estoque_formset(request.POST, instance=estoque_form, prefix='estoque')

        if form.is_valid() and formset.is_valid():
            form = form.save()
            formset.save()
            url = 'estoque:estoque_entrada_detail'
            return HttpResponseRedirect(resolve_url(url, form.pk))
    else:
        form = EstoqueForm(instance=estoque_form, prefix='main')
        formset = item_estoque_formset(instance=estoque_form, prefix='estoque')

    context = {'form': form, 'formset': formset}

    return render(request, template_name, context)

projeto/produto/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from .models import Produto
from .forms import ProdutoForm


def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    context = {'object_list': objects} # Dict que possui os objetos da classe produto

    return render(request, template_name, context)


def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj} # Dict que possui as descrições dos objetos da classe produto

    return render(request, template_name, context)


def produto_add(resquest):
    template_name = 'produto_form.html'
    return render(resquest, template_name)


class ProdutoCreate(CreateView):
    model = Produto
    template_name='produto_form.html'
    form_class= ProdutoForm


class ProdutoUpdate(UpdateView):
    model = Produto
    template_name='produto_form.html'
    form_class= ProdutoForm

projeto/core/templates/base.html
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico"> <!-- colocar favicon -->

    <title>Estoque</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
     <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
      body {
        margin-top: 60px
      }
      .ok {
        color: green;
      }
      .no {
        color: red;
      }

    </style>

    {% block css %}{% endblock css %}

  </head>
  <body>
    {% include "includes/nav.html" %}
    <div class="container">
      {% block content %}

      {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- retirada do Slim. e colocar a ordem 3.3.1 apagar o restante-->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  {% block js %}

  {% endblock js %}

  </body>
</html>

projeto/core/templates/includes/nav.html
<!--https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html-->
<!--Criação de um menu-->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Estoque</a> <!-- Define o nome do menu -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto"> <!-- Nome e links do menu-->
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'produto:produto_list' %}">Produtos</a>
                </li>

                <li class="nav-item dropdown"> <!-- Nome da lista que contém outros menus -->
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estoque</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Entrada</a>
                        <a class="dropdown-item" href="#">Saída</a>
                    </div>
                </li>
            </ul>
            <!-- Sistema de busca no menu
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
            -->
        </div>
    </nav>
</body>
</html>

projeto/core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %}

    {% block content %}
    <!-- Template de mensagem inicial simpes -->
    <div class="jumbotron">
        <div class="container">
            <h1>Bem-vindo!</h1>
            <p>Este é um sistema para controle de estoque.</p>
            <p> <a href="https://github.com/rg3915/estoque">Veja no GitHub </a></p>
        </div>
    </div>

    {% endblock content %}
</body>
</html>

projeto/estoque/templates/estoque_entrada_detail.html
{% extends "base.html" %}

{% block content %}

    <a href="{% url 'estoque:estoque_entrada_list' %}">Voltar </a>
    <h1>{{ object }}</h1>

    <div class="col-sm-6">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <th class="text-right">NF</th>
                    <td>{{ object.nf_formated}}</td>
                </tr>
                <tr>
                    <th class="text-right">Data</th>
                    <td>{{ object.created}}</td>
                </tr>
                <tr>
                    <th class="text-right">Funcionário</th>
                    <td>{{ object.funcionario.first_name }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Produto</th>
                <th>Quantidade</th>
                <th>Saldo</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object.estoques.all %}
            <tr>
                <td>{{ obj.produto }}</td>
                <td>{{ obj.quantidade }}</td>
                <td>{{ obj.saldo }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

projeto/estoque/templates/estoque_entrada_form.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}

    <style>
        span.required:after{
            content: " *";
            color: red;
         }

        .form-control{
            margin: 10px;
        }
    </style>

{% endblock css %}

{% block content %}
    <a href="{% url 'estoque:estoque_entrada_list' %}">Voltar </a>

    <div class="row">
        <div class="cols"> <!-- Formulario extenso col-sm-12 -->
            <form method="POST" novalidate>
                {% csrf_token %}
                <legend style="border-bottom: 1px solid #e5e5e5;" >
                    Estoque Entrada
                </legend>

                <div class="row">
                    <div class="col-sm-6">
                        {% for field in form.visible_fields %}
                            <div class="form-group{% if field.errors %} has-error {% endif%}">
                                <label for="{{ field.id_for_label }}">
                                    {% if field.field.required %}
                                        <span class="required">{{ field.label }}</span>
                                    {% else %}
                                        {{ field.label }}
                                    {% endif %}
                                </label>
                                {% render_field field class="form-control" %}

                                {% for error in field.errors %}
                                    <span class="text-muted">{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        {{ formset.management_form }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <legend style="border-bottom: 1px solid #e5e5e5;" >Produtos</legend>
                        <div id="estoque" class="form-inline">
                            {% for item_estoque_form in formset %}
                                <div id="item-{{ forloop.counter0 }}" class="form-group">
                                    {{ item_estoque_form|bootstrap }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <span id="add-item" class="btn btn-info" style="margin-top: 10px;" >
                    <i class="fa fa-plus"></i>Adicionar
                </span>

                <div class="row float-right">
                    <div class="col-sm-12" style="margin-top: 10px;">
                        <div class="form-inline buttons">
                            <button class="btn btn-primary" value="Save">
                                <i class="fa fa-floppy-o"></i>
                                Salvar
                            </button>
                            <a href="{% url 'estoque:estoque_entrada_list' %}" class="btn btn-danger">
                                <i class="fa fa-times"></i>
                                Cancelar
                            </a>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>


{% endblock content %}

{% block js %}

    <script>
        $(document).ready(function(){

           $('#add-item').click(function(ev) {
            ev.preventDefault();
            var count = $('#estoque').children().length;
            var tmplMarkup = $('#item-estoque').html();
            var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
            $('div#estoque').append(compiledTmpl);

            $('#id_estoque-TOTAL_FORMS').attr('value', count + 1);

            $('html, body').animate({
                scrollTop: $("#add-item").position().top - 200
            }, 800);
           });
        });
    </script>

    <script type="text/html" id="item-estoque">
        <div id="item-__prefix__" class="form-group" style="margin-top: 10px;">
            {{ formset.empty_form|bootstrap }}
        </div>
    </script>

{% endblock js %}

projeto/estoque/templates/estoque_entrada_list.html
{% extends "base.html" %}

{% block content %}

<h2>Estoque Entrada
    <!-- Criando um botão para adicionar que vai para protudo_form.html -->
    <span class="pull-right">
        <a href="{% url 'estoque:estoque_entrada_add' %}">
            <button type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span>Adicionar
            </button>
        </a>
    </span>
</h2>


{% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Item</th>
                <th>NF</th>
                <th>Data</th>
                <th>Funcionário</th>
            </tr>
        </thead>

        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{{ object.get_absolute_url }}">{{ object }}</a>
                    </td>
                    <td>{{ object.nf_formated }}</td>
                    <td>{{ object.created }}</td>
                    <td>{{ object.funcionario.first_name }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p class="alert alert-warning">Sem itens na lista</p>
{% endif %}

{% endblock content %}

projeto/produto/templates/produto_detail.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'produto:produto_list' %}">Voltar</a> <!-- link para voltar na pagína anterior -->
    <h1>
        {{ object }}
        <span class="pull-right">
            <a href="{% url 'produto:produto_edit' object.pk %}">
                <button type="button" class="btn btn-success"> <!-- botão para editar o produto-->
                    <span class="fa fa-pencil"></span>
                    Editar
                </button>
            </a>
        </span>
    </h1>

    <div class="col-sm-6">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <th class="text-right">Importado</th>
                    <td>
                        {% if object.importado %} <!-- Caso objeto for importado, faça: -->
                            <i class="fa fa-check-circle ok"></i>
                        {% else %}
                            <i class="fa fa-minus-circle no"></i>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th class="text-right">NCM</th>
                    <td>{{ object.ncm }}</td>
                </tr>
                <tr>
                    <th class="text-right">Preço</th>
                    <td>R$ {{ object.preco }}</td>
                </tr>
                <tr>
                    <th class="text-right">Estoque</th>
                    <td>{{ object.estoque }}</td>
                </tr>
                <tr>
                    <th class="text-right">Estoque Mínimo</th>
                    <td>{{ object.estoque_minimo }}</td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock content %}

projeto/produto/templates/produto_form.html
{% extends "base.html" %}

<!-- https://github.com/jazzband/django-widget-tweaks -->
{% load widget_tweaks %}

{% block css %}
    <style>
        span.required:after{
            content: " *";
            color: red;
            }
    </style>
{% endblock css %}

{% block content %}

    <form method="POST" novalidate>
        {% csrf_token %} <!-- para postar no formulario -->
        {% for field in form.visible_fields %}
            <div class="form-group{% if field.errors %} has-error {% endif%}">
                <label for="{{ field.id_for_label }}">
                    {% if field.field.required %}
                        <span class="required">{{ field.label }}</span>
                    {% else %}
                        {{ field.label }}
                    {% endif %}
                </label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                    <span class="text-muted">{{ error }}</span>
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Cadastrar</button>
    </form>

{% endblock content %}

{% block js %}
    <script>
        $('#id_importado').removeClass('form-control')
    </script>
{% endblock js %}

projeto/produto/templates/produto_list.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h2>Lista de Produtos
        <!-- Criando um botão para adicionar que vai para protudo_form.html -->
        <span class="pull-right">
            <a href="{% url 'produto:produto_add' %}  ">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span>Adicionar
                </button>
            </a>
        </span>
    </h2>

    {% if object_list %}
        <!-- Criação da tabela para exibir as lista de produtos-->


        <table class="table table-striped">
            <thead>
                <tr> <!-- Coluna da tabela -->
                    <th>Importado</th>
                    <th>NCM</th>
                    <th>Produto</th>
                    <th>Preço</th>
                    <th class="text-center">Estoque</th>
                    <th class="text-center">Estoque mínimo</th>
                </tr>
            </thead>

            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        {% if object.importado %} <!-- Caso objeto for importado, faça: -->
                            <i class="fa fa-check-circle ok"></i>
                        {% else %}
                            <i class="fa fa-minus-circle no"></i>
                        {% endif %}
                    </td>
                    <td>{{ object.ncm }}</td>
                    <td>
                        <a href="{{ object.get_absolute_url }}"> {{ object.produto }} </a>
                    </td>
                    <td>R$ <span class="pull-right">{{ object.preco }}</span></td>
                    <td class="text-center">{{ object.estoque }}</td>
                    <td class="text-center">{{ object.estoque_minimo }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %} <!-- Caso não tenha na lista de produto -->
        <p class="alert alert-warning">Sem itens na lista.</p>
    {% endif %}
</div>

{% endblock content %}